### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#49]
Hi, this is just a list of features and modifications that I would like to implement in the future. 
They have different priorities and are not in any particular order but still would be nice to have them.
(also I wanted to try the tasklist)

```[tasklist]
### Tasks
- [ ] **Fast reset**: qick has this functionality, it's just a problem of how to implement it. Possibly, we could add to the qubit object the required classification parameters, as well as a specific pulse sequence to execute before the measurement/s
- [ ] **Extend sweepers to be on channels when multiple pulses are fired**: to do it, we should use sweepers as we do now for delay and bias sweepers: defining a new register for every sweeper and not leveraging the existing standard one, to avoid changing the parameters of all the pulses
- [x] **Decouple acquisition and pulse measurement**: currently, a measurement pulse has two roles: (1) fire the pulse, (2) acquire. Although this is useful in computing applications, is limiting in general (#89)
- [x] **Add more pulse shapes**: at least all the ones already defined in the Qick library could/should be added (#93)
- [ ] **Add support for IQ generators**: we have them in the multiplexed firmware for the ZCU216 and they are controlled with [this method](https://qick-docs.readthedocs.io/en/latest/_modules/qick/drivers/generator.html#AxisConstantIQ). They are useless for now, but I don't see why qibosoq shouldn't support them
```

**Comment by rodolfocarobene** [comment]
Closing as outdated
